package FrontEndIdl;


/**
* FrontEndIdl/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/LibraryManagementSystemProject/src/FrontEnd.idl
* Saturday, March 30, 2019 7:01:18 PM EDT
*/

public interface FrontEndOperations 
{
  String addItem (String userId, String itemId, String itemName, int quantity);
  String listItemAvailability (String managerId);
  String removeItem (String userId, String itemId, int quantity);
  String borrowItem (String userId, String itemId);
  String addToWaitingList (String userId, String itemId);
  String findItem (String userId, String itemName, boolean fromOtherServer);
  String returnItem (String userId, String itemId);
  String exchangeItem (String userId, String newItemId, String oldItemId);
  void shutdown ();
} // interface FrontEndOperations
