package FrontEndIdl;


/**
* FrontEndIdl/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/LibraryManagementSystemProject/src/FrontEnd.idl
* Saturday, March 30, 2019 7:01:18 PM EDT
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
