package FrontEndIdl;


/**
* FrontEndIdl/FrontEndPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/LibraryManagementSystemProject/src/FrontEnd.idl
* Saturday, March 30, 2019 7:01:18 PM EDT
*/

public abstract class FrontEndPOA extends org.omg.PortableServer.Servant
 implements FrontEndIdl.FrontEndOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addItem", new java.lang.Integer (0));
    _methods.put ("listItemAvailability", new java.lang.Integer (1));
    _methods.put ("removeItem", new java.lang.Integer (2));
    _methods.put ("borrowItem", new java.lang.Integer (3));
    _methods.put ("addToWaitingList", new java.lang.Integer (4));
    _methods.put ("findItem", new java.lang.Integer (5));
    _methods.put ("returnItem", new java.lang.Integer (6));
    _methods.put ("exchangeItem", new java.lang.Integer (7));
    _methods.put ("shutdown", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FrontEndIdl/FrontEnd/addItem
       {
         String userId = in.read_string ();
         String itemId = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.addItem (userId, itemId, itemName, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FrontEndIdl/FrontEnd/listItemAvailability
       {
         String managerId = in.read_string ();
         String $result = null;
         $result = this.listItemAvailability (managerId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // FrontEndIdl/FrontEnd/removeItem
       {
         String userId = in.read_string ();
         String itemId = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.removeItem (userId, itemId, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // FrontEndIdl/FrontEnd/borrowItem
       {
         String userId = in.read_string ();
         String itemId = in.read_string ();
         String $result = null;
         $result = this.borrowItem (userId, itemId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // FrontEndIdl/FrontEnd/addToWaitingList
       {
         String userId = in.read_string ();
         String itemId = in.read_string ();
         String $result = null;
         $result = this.addToWaitingList (userId, itemId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // FrontEndIdl/FrontEnd/findItem
       {
         String userId = in.read_string ();
         String itemName = in.read_string ();
         boolean fromOtherServer = in.read_boolean ();
         String $result = null;
         $result = this.findItem (userId, itemName, fromOtherServer);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // FrontEndIdl/FrontEnd/returnItem
       {
         String userId = in.read_string ();
         String itemId = in.read_string ();
         String $result = null;
         $result = this.returnItem (userId, itemId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // FrontEndIdl/FrontEnd/exchangeItem
       {
         String userId = in.read_string ();
         String newItemId = in.read_string ();
         String oldItemId = in.read_string ();
         String $result = null;
         $result = this.exchangeItem (userId, newItemId, oldItemId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // FrontEndIdl/FrontEnd/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FrontEndIdl/FrontEnd:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FrontEnd _this() 
  {
    return FrontEndHelper.narrow(
    super._this_object());
  }

  public FrontEnd _this(org.omg.CORBA.ORB orb) 
  {
    return FrontEndHelper.narrow(
    super._this_object(orb));
  }


} // class FrontEndPOA
